### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/mujeres-tea#11]
- [x] Handle `resize` event for nav
- [x] Add contact page
- [ ] 404 page
- [ ] Media viewer
  - [ ] Image viewer
    - [ ] Print control
    - [ ] Full screen control
    - [ ] Download control
  - [ ] Pdf viewer
    - [x] Thumbnail
    - [x] View page
    - [x] Pages navigation
    - [ ] Print control
    - [ ] Full screen control
    - [ ] Download control
  - [ ] Video viewer
    - [ ] Thumbnail
    - [ ] View video
